In [1]:
# Packagaes in python 

# Modules 
# Packages

# Find the package your after (Best place is gitHub)
# Install the package (pip install)



In [1]:
#Numpy arrays 

import numpy as np 

In [2]:
#numpy array will only accept one data type 
#lots of goof functions with a array 
#can do a 2d array (matrix)

a = list(range(20))

# Create a numpy array by passing in a list 
b = np.array(a)

In [7]:
# Look at all of the functions that can be used with arrays
b.mean()

9.5

In [3]:
# Slicing Arrays 
# When slicing arrays you are working with a reference to the original array 

b[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [6]:
b[2:7] = 111

In [7]:
b

array([  0,   1, 111, 111, 111, 111, 111,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [10]:
c = b.copy()

In [15]:
c[0]= 555

---

In [17]:
# Financial statement analysis - Homework 

In [29]:
"""
Scenario: You are a Data scientist working for a consuting firm. 
One of your collegues from the auditing departmenthas asked you 
to help them assess the financial statement of organisation x.

You have been supplied with two list of data: monthly revenue
and monthly expenses for the financial year in question. 

Your task is to calculate the following financial metrics:

profit for each month.
Profit after tax for each month (30%)
Profit margin for each month: Profit after tax divided by revenue
Good months: where profit after tax was greater than the mean for the year
Bad months: where profit after tax was less than the mean for the year
The best month: Where profit after tax was max for the year.
The worst month: 

===============================================================

All results in lists.

Dollar values calculated to $0.01 
precision but presented in units of $1k

results for profit margin ratio presented in % with 0dp

its ok for tax to be negative


round()
max()
min()


print("")

In [76]:
# THIS WAS MY ATTEMPT

#Data 

import numpy 

revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

revenueA = numpy.array(revenue)
expensesA = numpy.array(expenses)

#Profit for each month

profit = revenueA - expensesA
profit

#Profit after tax for each month (30%)


profitAT = profit * 0.70
profitATR = profitAT.round(2)
profitATR

#Profit margin for each month: Profit after tax divided by revenue
profitM = (profitAT/revenueA).round(2) * 100
profitM

#Good months: where profit after tax was greater than the mean for the year
mean = profitAT.mean()
mean 

goodM = profitAT > mean
goodM


#Bad months: where profit after tax was less than the mean for the year

badM = profitAT < mean
badM

#The best month: Where profit after tax was max for the year.

bestM = profitAT.max()
bestM.round(2)

#The worst month: Where profit after tax was min for the year.
worstM = profitAT.min()
worstM = worstM.round(2)

#Print Results
print ("Revenue :") 
print (revenueA)
print ("Expenses :") 
print (expensesA)
print ("Profit :")
print(profit)
print ("Profit after tax :")
print (profitATR)
print ("Profit margin :")
print (profitM)
print ("Good months :")
print (goodM)
print ("Bad months :")
print (badM)
print ("Best month :")
print (bestM)
print ("Worst month :")
print (worstM)


Revenue :
[ 14574.49   7606.46   8611.41   9175.41   8058.65   8105.44  11496.28
   9766.09  10305.32  14379.96  10713.97  15433.5 ]
Expenses :
[ 12051.82   5695.07  12319.2   12089.72   8658.57    840.2    3285.73
   5821.12   6976.93  16618.61  10054.37   3803.96]
Profit :
[  2522.67   1911.39  -3707.79  -2914.31   -599.92   7265.24   8210.55
   3944.97   3328.39  -2238.65    659.6   11629.54]
Profit after tax :
[ 1765.87  1337.97 -2595.45 -2040.02  -419.94  5085.67  5747.38  2761.48
  2329.87 -1567.06   461.72  8140.68]
Profit margin :
[ 12.  18. -30. -22.  -5.  63.  50.  28.  23. -11.   4.  53.]
Good months :
[ True False False False False  True  True  True  True False False  True]
Bad months :
[False  True  True  True  True False False False False  True  True False]
Best month :
8140.678
Worst month :
-2595.45


---

In [73]:
###original fill in the blanks

#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

#Solution
#Calculate Profit As The Differences Between Revenue And Expenses
profit = []
for i in range (0, len(revenue)):
    profit.append(revenue[i] - expenses [i])
profit

#Calculate Tax As 30% Of Profit And Round To 2 Decimal Points
tax = [round(i *0.30, 2) for i in profit]
tax

#Calculate Profit Remaining After Tax Is Deducted
profit_after_tax = []
for i in range (0, len(tax)):
    profit_after_tax.append(profit[i] - tax[i])
profit_after_tax

#Calculate The Profit Margin As Profit After Tax Over Revenue
#Round To 2 Decimal Points, Then Multiply By 100 To Get %
profit_margin = []
for i in range (0, len(revenue)):
    profit_margin.append(profit_after_tax[i] / revenue[i])
profit_margin

profit_margin = [round((i),2) for i in profit_margin]

profit_margin = [i * 100 for i in profit_margin]
profit_margin

#Calculate The Mean Profit After Tax For The 12 Months
mean_pat = sum(profit_after_tax) / len(profit_margin)
mean_pat

#Find The Months With Above-Mean Profit After Tax
good_months = []
for i in range (0, len(revenue)):
    good_months.append(profit_after_tax[i] > mean_pat)
good_months

#Bad Months Are The Opposite Of Good Months!
bad_months = []
for i in range (0, len(revenue)):
    bad_months.append(not (good_months[i]))
bad_months

#The Best Month Is Where Profit After Tax Was Equal To The Maximum
best_month = []
for i in range (0, len(revenue)):
    best_month.append(profit_after_tax[i] == max(profit_after_tax))
best_month

#The Worst Month Is Where Profit After Tax Was Equal To The Minimum
worst_month = []
for i in range (0, len(revenue)):
    worst_month.append(profit_after_tax[i] == min(profit_after_tax))
worst_month

#Convert All Calculations To Units Of One Thousand Dollars
revenue_1000 = [round(i, -3) for i in revenue]
expenses_1000 = [round(i, -3) for i in expenses]
profit_1000 = [round(i, -3) for i in profit]
profit_after_tax_1000 = [round(i, -3) for i in profit_after_tax]

revenue_1000 = [int(i) for i in revenue_1000]
expenses_1000 = [int(i) for i in expenses_1000]
profit_1000 = [int(i) for i in profit_1000]
profit_after_tax_1000 = [int(i) for i in profit_after_tax_1000]

#Print Results
print ("Revenue :") 
print (revenue_1000)
print ("Expenses :") 
print (expenses_1000)
print ("Profit :")
print(profit_1000)
print ("Profit after tax :")
print (profit_after_tax_1000)
print ("Profit margin :")
print (profit_margin)
print ("Good months :")
print (good_months)
print ("Bad months :")
print (bad_months)
print ("Best month :")
print (best_month)
print ("Worst month :")
print (worst_month)


Revenue :
[15000, 8000, 9000, 9000, 8000, 8000, 11000, 10000, 10000, 14000, 11000, 15000]
Expenses :
[12000, 6000, 12000, 12000, 9000, 1000, 3000, 6000, 7000, 17000, 10000, 4000]
Profit :
[3000, 2000, -4000, -3000, -1000, 7000, 8000, 4000, 3000, -2000, 1000, 12000]
Profit after tax :
[2000, 1000, -3000, -2000, 0, 5000, 6000, 3000, 2000, -2000, 0, 8000]
Profit margin :
[12.0, 18.0, -30.0, -22.0, -5.0, 63.0, 50.0, 28.000000000000004, 23.0, -11.0, 4.0, 53.0]
Good months :
[True, False, False, False, False, True, True, True, True, False, False, True]
Bad months :
[False, True, True, True, True, False, False, False, False, True, True, False]
Best month :
[False, False, False, False, False, False, False, False, False, False, False, True]
Worst month :
[False, False, True, False, False, False, False, False, False, False, False, False]


In [2]:
####HOMEWORK RUN THROUGH 

#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]


In [3]:
# CALCULATING PROFIT 

profit = []

for i in range(0,len(revenue)):
    profit.append(revenue[i] - expenses[i])

profit

[2522.67,
 1911.3900000000003,
 -3707.790000000001,
 -2914.3099999999995,
 -599.9200000000001,
 7265.24,
 8210.550000000001,
 3944.9700000000003,
 3328.3899999999994,
 -2238.6500000000015,
 659.5999999999985,
 11629.54]

In [7]:
# calculating tax (profit * 30%)
tax = [round(i*0.3,2) for i in profit]
tax

[756.8,
 573.42,
 -1112.34,
 -874.29,
 -179.98,
 2179.57,
 2463.17,
 1183.49,
 998.52,
 -671.6,
 197.88,
 3488.86]

In [9]:
#profit after tax
profitAfterTax = []

for i in range(0, len(profit)):
    profitAfterTax.append(profit[i]-tax[i])
profitAfterTax

[1765.8700000000001,
 1337.9700000000003,
 -2595.4500000000007,
 -2040.0199999999995,
 -419.94000000000005,
 5085.67,
 5747.380000000001,
 2761.4800000000005,
 2329.8699999999994,
 -1567.0500000000015,
 461.71999999999855,
 8140.68]

In [15]:
# profit margin after tax

profitMargin = []

for i in range(0,len(profit)):
    profitMargin.append(profitAfterTax[i]/revenue[i])

profitMargin = [round((i*100),2) for i in profitMargin]
profitMargin

[12.12,
 17.59,
 -30.14,
 -22.23,
 -5.21,
 62.74,
 49.99,
 28.28,
 22.61,
 -10.9,
 4.31,
 52.75]

In [16]:
mean_pat = sum(profitAfterTax)/len(profitAfterTax)
mean_pat

1750.6816666666666

In [20]:
goodMonths = []
badMonths = []
for i in range(0, len(profit)):
    goodMonths.append(profitAfterTax[i] > mean_pat)
    badMonths.append(profitAfterTax[i] < mean_pat)
    
badMonths

[False, True, True, True, True, False, False, False, False, True, True, False]

In [22]:
bestMonth = max(profitAfterTax)
bestMonth

8140.68

In [23]:
worstMonth = min(profitAfterTax)
worstMonth

-2595.4500000000007